title: "CMKC Keyboard Docs"
remote_theme: just-the-docs/just-the-docs
color_scheme: "dark"
search_enabled: true
logo: "Docs/Images/cmkc_icon.png"
favicon_ico: "Docs/Images/cmkc_icon.png"


aux_links:
  "CMKC on GitHub":
    - "https://github.com/thomasdevine01/cmkc-keyboard

nav_external_links:
  "CMKC on GitHub":
    - "https://github.com/thomasdevine01/cmkc-keyboard